// Generated by scripts/gen_sincos_interp.py. Do not edit by hand.

rom_sin_base[0]  = 12'h000;
rom_sin_slope[0] = 8'sh32;
rom_cos_base[0]  = 12'hff8;
rom_cos_slope[0] = 8'sh00;

rom_sin_base[1]  = 12'h032;
rom_sin_slope[1] = 8'sh32;
rom_cos_base[1]  = 12'hff8;
rom_cos_slope[1] = -8'sh01;

rom_sin_base[2]  = 12'h064;
rom_sin_slope[2] = 8'sh32;
rom_cos_base[2]  = 12'hff7;
rom_cos_slope[2] = -8'sh02;

rom_sin_base[3]  = 12'h096;
rom_sin_slope[3] = 8'sh33;
rom_cos_base[3]  = 12'hff5;
rom_cos_slope[3] = -8'sh02;

rom_sin_base[4]  = 12'h0c9;
rom_sin_slope[4] = 8'sh32;
rom_cos_base[4]  = 12'hff3;
rom_cos_slope[4] = -8'sh03;

rom_sin_base[5]  = 12'h0fb;
rom_sin_slope[5] = 8'sh32;
rom_cos_base[5]  = 12'hff0;
rom_cos_slope[5] = -8'sh03;

rom_sin_base[6]  = 12'h12d;
rom_sin_slope[6] = 8'sh32;
rom_cos_base[6]  = 12'hfed;
rom_cos_slope[6] = -8'sh04;

rom_sin_base[7]  = 12'h15f;
rom_sin_slope[7] = 8'sh32;
rom_cos_base[7]  = 12'hfe9;
rom_cos_slope[7] = -8'sh05;

rom_sin_base[8]  = 12'h191;
rom_sin_slope[8] = 8'sh32;
rom_cos_base[8]  = 12'hfe4;
rom_cos_slope[8] = -8'sh05;

rom_sin_base[9]  = 12'h1c3;
rom_sin_slope[9] = 8'sh31;
rom_cos_base[9]  = 12'hfdf;
rom_cos_slope[9] = -8'sh06;

rom_sin_base[10]  = 12'h1f4;
rom_sin_slope[10] = 8'sh32;
rom_cos_base[10]  = 12'hfd9;
rom_cos_slope[10] = -8'sh06;

rom_sin_base[11]  = 12'h226;
rom_sin_slope[11] = 8'sh32;
rom_cos_base[11]  = 12'hfd3;
rom_cos_slope[11] = -8'sh07;

rom_sin_base[12]  = 12'h258;
rom_sin_slope[12] = 8'sh31;
rom_cos_base[12]  = 12'hfcc;
rom_cos_slope[12] = -8'sh08;

rom_sin_base[13]  = 12'h289;
rom_sin_slope[13] = 8'sh32;
rom_cos_base[13]  = 12'hfc4;
rom_cos_slope[13] = -8'sh08;

rom_sin_base[14]  = 12'h2bb;
rom_sin_slope[14] = 8'sh31;
rom_cos_base[14]  = 12'hfbc;
rom_cos_slope[14] = -8'sh09;

rom_sin_base[15]  = 12'h2ec;
rom_sin_slope[15] = 8'sh32;
rom_cos_base[15]  = 12'hfb3;
rom_cos_slope[15] = -8'sh0a;

rom_sin_base[16]  = 12'h31e;
rom_sin_slope[16] = 8'sh31;
rom_cos_base[16]  = 12'hfa9;
rom_cos_slope[16] = -8'sh0a;

rom_sin_base[17]  = 12'h34f;
rom_sin_slope[17] = 8'sh31;
rom_cos_base[17]  = 12'hf9f;
rom_cos_slope[17] = -8'sh0a;

rom_sin_base[18]  = 12'h380;
rom_sin_slope[18] = 8'sh31;
rom_cos_base[18]  = 12'hf95;
rom_cos_slope[18] = -8'sh0c;

rom_sin_base[19]  = 12'h3b1;
rom_sin_slope[19] = 8'sh30;
rom_cos_base[19]  = 12'hf89;
rom_cos_slope[19] = -8'sh0c;

rom_sin_base[20]  = 12'h3e1;
rom_sin_slope[20] = 8'sh31;
rom_cos_base[20]  = 12'hf7d;
rom_cos_slope[20] = -8'sh0c;

rom_sin_base[21]  = 12'h412;
rom_sin_slope[21] = 8'sh30;
rom_cos_base[21]  = 12'hf71;
rom_cos_slope[21] = -8'sh0d;

rom_sin_base[22]  = 12'h442;
rom_sin_slope[22] = 8'sh31;
rom_cos_base[22]  = 12'hf64;
rom_cos_slope[22] = -8'sh0e;

rom_sin_base[23]  = 12'h473;
rom_sin_slope[23] = 8'sh30;
rom_cos_base[23]  = 12'hf56;
rom_cos_slope[23] = -8'sh0e;

rom_sin_base[24]  = 12'h4a3;
rom_sin_slope[24] = 8'sh30;
rom_cos_base[24]  = 12'hf48;
rom_cos_slope[24] = -8'sh0f;

rom_sin_base[25]  = 12'h4d3;
rom_sin_slope[25] = 8'sh2f;
rom_cos_base[25]  = 12'hf39;
rom_cos_slope[25] = -8'sh0f;

rom_sin_base[26]  = 12'h502;
rom_sin_slope[26] = 8'sh30;
rom_cos_base[26]  = 12'hf2a;
rom_cos_slope[26] = -8'sh10;

rom_sin_base[27]  = 12'h532;
rom_sin_slope[27] = 8'sh2f;
rom_cos_base[27]  = 12'hf1a;
rom_cos_slope[27] = -8'sh11;

rom_sin_base[28]  = 12'h561;
rom_sin_slope[28] = 8'sh2f;
rom_cos_base[28]  = 12'hf09;
rom_cos_slope[28] = -8'sh11;

rom_sin_base[29]  = 12'h590;
rom_sin_slope[29] = 8'sh2f;
rom_cos_base[29]  = 12'hef8;
rom_cos_slope[29] = -8'sh12;

rom_sin_base[30]  = 12'h5bf;
rom_sin_slope[30] = 8'sh2f;
rom_cos_base[30]  = 12'hee6;
rom_cos_slope[30] = -8'sh12;

rom_sin_base[31]  = 12'h5ee;
rom_sin_slope[31] = 8'sh2e;
rom_cos_base[31]  = 12'hed4;
rom_cos_slope[31] = -8'sh13;

rom_sin_base[32]  = 12'h61c;
rom_sin_slope[32] = 8'sh2f;
rom_cos_base[32]  = 12'hec1;
rom_cos_slope[32] = -8'sh14;

rom_sin_base[33]  = 12'h64b;
rom_sin_slope[33] = 8'sh2e;
rom_cos_base[33]  = 12'head;
rom_cos_slope[33] = -8'sh14;

rom_sin_base[34]  = 12'h679;
rom_sin_slope[34] = 8'sh2d;
rom_cos_base[34]  = 12'he99;
rom_cos_slope[34] = -8'sh14;

rom_sin_base[35]  = 12'h6a6;
rom_sin_slope[35] = 8'sh2e;
rom_cos_base[35]  = 12'he85;
rom_cos_slope[35] = -8'sh15;

rom_sin_base[36]  = 12'h6d4;
rom_sin_slope[36] = 8'sh2d;
rom_cos_base[36]  = 12'he70;
rom_cos_slope[36] = -8'sh16;

rom_sin_base[37]  = 12'h701;
rom_sin_slope[37] = 8'sh2d;
rom_cos_base[37]  = 12'he5a;
rom_cos_slope[37] = -8'sh16;

rom_sin_base[38]  = 12'h72e;
rom_sin_slope[38] = 8'sh2d;
rom_cos_base[38]  = 12'he44;
rom_cos_slope[38] = -8'sh17;

rom_sin_base[39]  = 12'h75b;
rom_sin_slope[39] = 8'sh2c;
rom_cos_base[39]  = 12'he2d;
rom_cos_slope[39] = -8'sh18;

rom_sin_base[40]  = 12'h787;
rom_sin_slope[40] = 8'sh2c;
rom_cos_base[40]  = 12'he15;
rom_cos_slope[40] = -8'sh18;

rom_sin_base[41]  = 12'h7b3;
rom_sin_slope[41] = 8'sh2c;
rom_cos_base[41]  = 12'hdfd;
rom_cos_slope[41] = -8'sh18;

rom_sin_base[42]  = 12'h7df;
rom_sin_slope[42] = 8'sh2b;
rom_cos_base[42]  = 12'hde5;
rom_cos_slope[42] = -8'sh19;

rom_sin_base[43]  = 12'h80a;
rom_sin_slope[43] = 8'sh2c;
rom_cos_base[43]  = 12'hdcc;
rom_cos_slope[43] = -8'sh1a;

rom_sin_base[44]  = 12'h836;
rom_sin_slope[44] = 8'sh2b;
rom_cos_base[44]  = 12'hdb2;
rom_cos_slope[44] = -8'sh1a;

rom_sin_base[45]  = 12'h861;
rom_sin_slope[45] = 8'sh2a;
rom_cos_base[45]  = 12'hd98;
rom_cos_slope[45] = -8'sh1a;

rom_sin_base[46]  = 12'h88b;
rom_sin_slope[46] = 8'sh2a;
rom_cos_base[46]  = 12'hd7e;
rom_cos_slope[46] = -8'sh1b;

rom_sin_base[47]  = 12'h8b5;
rom_sin_slope[47] = 8'sh2a;
rom_cos_base[47]  = 12'hd63;
rom_cos_slope[47] = -8'sh1c;

rom_sin_base[48]  = 12'h8df;
rom_sin_slope[48] = 8'sh2a;
rom_cos_base[48]  = 12'hd47;
rom_cos_slope[48] = -8'sh1c;

rom_sin_base[49]  = 12'h909;
rom_sin_slope[49] = 8'sh29;
rom_cos_base[49]  = 12'hd2b;
rom_cos_slope[49] = -8'sh1d;

rom_sin_base[50]  = 12'h932;
rom_sin_slope[50] = 8'sh29;
rom_cos_base[50]  = 12'hd0e;
rom_cos_slope[50] = -8'sh1d;

rom_sin_base[51]  = 12'h95b;
rom_sin_slope[51] = 8'sh28;
rom_cos_base[51]  = 12'hcf1;
rom_cos_slope[51] = -8'sh1d;

rom_sin_base[52]  = 12'h983;
rom_sin_slope[52] = 8'sh28;
rom_cos_base[52]  = 12'hcd4;
rom_cos_slope[52] = -8'sh1f;

rom_sin_base[53]  = 12'h9ab;
rom_sin_slope[53] = 8'sh28;
rom_cos_base[53]  = 12'hcb5;
rom_cos_slope[53] = -8'sh1e;

rom_sin_base[54]  = 12'h9d3;
rom_sin_slope[54] = 8'sh27;
rom_cos_base[54]  = 12'hc97;
rom_cos_slope[54] = -8'sh1f;

rom_sin_base[55]  = 12'h9fa;
rom_sin_slope[55] = 8'sh27;
rom_cos_base[55]  = 12'hc78;
rom_cos_slope[55] = -8'sh20;

rom_sin_base[56]  = 12'ha21;
rom_sin_slope[56] = 8'sh27;
rom_cos_base[56]  = 12'hc58;
rom_cos_slope[56] = -8'sh20;

rom_sin_base[57]  = 12'ha48;
rom_sin_slope[57] = 8'sh26;
rom_cos_base[57]  = 12'hc38;
rom_cos_slope[57] = -8'sh21;

rom_sin_base[58]  = 12'ha6e;
rom_sin_slope[58] = 8'sh26;
rom_cos_base[58]  = 12'hc17;
rom_cos_slope[58] = -8'sh21;

rom_sin_base[59]  = 12'ha94;
rom_sin_slope[59] = 8'sh25;
rom_cos_base[59]  = 12'hbf6;
rom_cos_slope[59] = -8'sh21;

rom_sin_base[60]  = 12'hab9;
rom_sin_slope[60] = 8'sh25;
rom_cos_base[60]  = 12'hbd5;
rom_cos_slope[60] = -8'sh22;

rom_sin_base[61]  = 12'hade;
rom_sin_slope[61] = 8'sh25;
rom_cos_base[61]  = 12'hbb3;
rom_cos_slope[61] = -8'sh22;

rom_sin_base[62]  = 12'hb03;
rom_sin_slope[62] = 8'sh24;
rom_cos_base[62]  = 12'hb91;
rom_cos_slope[62] = -8'sh23;

rom_sin_base[63]  = 12'hb27;
rom_sin_slope[63] = 8'sh24;
rom_cos_base[63]  = 12'hb6e;
rom_cos_slope[63] = -8'sh23;

rom_sin_base[64]  = 12'hb4b;
rom_sin_slope[64] = 8'sh23;
rom_cos_base[64]  = 12'hb4b;
rom_cos_slope[64] = -8'sh24;

rom_sin_base[65]  = 12'hb6e;
rom_sin_slope[65] = 8'sh23;
rom_cos_base[65]  = 12'hb27;
rom_cos_slope[65] = -8'sh24;

rom_sin_base[66]  = 12'hb91;
rom_sin_slope[66] = 8'sh22;
rom_cos_base[66]  = 12'hb03;
rom_cos_slope[66] = -8'sh25;

rom_sin_base[67]  = 12'hbb3;
rom_sin_slope[67] = 8'sh22;
rom_cos_base[67]  = 12'hade;
rom_cos_slope[67] = -8'sh25;

rom_sin_base[68]  = 12'hbd5;
rom_sin_slope[68] = 8'sh21;
rom_cos_base[68]  = 12'hab9;
rom_cos_slope[68] = -8'sh25;

rom_sin_base[69]  = 12'hbf6;
rom_sin_slope[69] = 8'sh21;
rom_cos_base[69]  = 12'ha94;
rom_cos_slope[69] = -8'sh26;

rom_sin_base[70]  = 12'hc17;
rom_sin_slope[70] = 8'sh21;
rom_cos_base[70]  = 12'ha6e;
rom_cos_slope[70] = -8'sh26;

rom_sin_base[71]  = 12'hc38;
rom_sin_slope[71] = 8'sh20;
rom_cos_base[71]  = 12'ha48;
rom_cos_slope[71] = -8'sh27;

rom_sin_base[72]  = 12'hc58;
rom_sin_slope[72] = 8'sh20;
rom_cos_base[72]  = 12'ha21;
rom_cos_slope[72] = -8'sh27;

rom_sin_base[73]  = 12'hc78;
rom_sin_slope[73] = 8'sh1f;
rom_cos_base[73]  = 12'h9fa;
rom_cos_slope[73] = -8'sh27;

rom_sin_base[74]  = 12'hc97;
rom_sin_slope[74] = 8'sh1e;
rom_cos_base[74]  = 12'h9d3;
rom_cos_slope[74] = -8'sh28;

rom_sin_base[75]  = 12'hcb5;
rom_sin_slope[75] = 8'sh1f;
rom_cos_base[75]  = 12'h9ab;
rom_cos_slope[75] = -8'sh28;

rom_sin_base[76]  = 12'hcd4;
rom_sin_slope[76] = 8'sh1d;
rom_cos_base[76]  = 12'h983;
rom_cos_slope[76] = -8'sh28;

rom_sin_base[77]  = 12'hcf1;
rom_sin_slope[77] = 8'sh1d;
rom_cos_base[77]  = 12'h95b;
rom_cos_slope[77] = -8'sh29;

rom_sin_base[78]  = 12'hd0e;
rom_sin_slope[78] = 8'sh1d;
rom_cos_base[78]  = 12'h932;
rom_cos_slope[78] = -8'sh29;

rom_sin_base[79]  = 12'hd2b;
rom_sin_slope[79] = 8'sh1c;
rom_cos_base[79]  = 12'h909;
rom_cos_slope[79] = -8'sh2a;

rom_sin_base[80]  = 12'hd47;
rom_sin_slope[80] = 8'sh1c;
rom_cos_base[80]  = 12'h8df;
rom_cos_slope[80] = -8'sh2a;

rom_sin_base[81]  = 12'hd63;
rom_sin_slope[81] = 8'sh1b;
rom_cos_base[81]  = 12'h8b5;
rom_cos_slope[81] = -8'sh2a;

rom_sin_base[82]  = 12'hd7e;
rom_sin_slope[82] = 8'sh1a;
rom_cos_base[82]  = 12'h88b;
rom_cos_slope[82] = -8'sh2a;

rom_sin_base[83]  = 12'hd98;
rom_sin_slope[83] = 8'sh1a;
rom_cos_base[83]  = 12'h861;
rom_cos_slope[83] = -8'sh2b;

rom_sin_base[84]  = 12'hdb2;
rom_sin_slope[84] = 8'sh1a;
rom_cos_base[84]  = 12'h836;
rom_cos_slope[84] = -8'sh2c;

rom_sin_base[85]  = 12'hdcc;
rom_sin_slope[85] = 8'sh19;
rom_cos_base[85]  = 12'h80a;
rom_cos_slope[85] = -8'sh2b;

rom_sin_base[86]  = 12'hde5;
rom_sin_slope[86] = 8'sh18;
rom_cos_base[86]  = 12'h7df;
rom_cos_slope[86] = -8'sh2c;

rom_sin_base[87]  = 12'hdfd;
rom_sin_slope[87] = 8'sh18;
rom_cos_base[87]  = 12'h7b3;
rom_cos_slope[87] = -8'sh2c;

rom_sin_base[88]  = 12'he15;
rom_sin_slope[88] = 8'sh18;
rom_cos_base[88]  = 12'h787;
rom_cos_slope[88] = -8'sh2c;

rom_sin_base[89]  = 12'he2d;
rom_sin_slope[89] = 8'sh17;
rom_cos_base[89]  = 12'h75b;
rom_cos_slope[89] = -8'sh2d;

rom_sin_base[90]  = 12'he44;
rom_sin_slope[90] = 8'sh16;
rom_cos_base[90]  = 12'h72e;
rom_cos_slope[90] = -8'sh2d;

rom_sin_base[91]  = 12'he5a;
rom_sin_slope[91] = 8'sh16;
rom_cos_base[91]  = 12'h701;
rom_cos_slope[91] = -8'sh2d;

rom_sin_base[92]  = 12'he70;
rom_sin_slope[92] = 8'sh15;
rom_cos_base[92]  = 12'h6d4;
rom_cos_slope[92] = -8'sh2e;

rom_sin_base[93]  = 12'he85;
rom_sin_slope[93] = 8'sh14;
rom_cos_base[93]  = 12'h6a6;
rom_cos_slope[93] = -8'sh2d;

rom_sin_base[94]  = 12'he99;
rom_sin_slope[94] = 8'sh14;
rom_cos_base[94]  = 12'h679;
rom_cos_slope[94] = -8'sh2e;

rom_sin_base[95]  = 12'head;
rom_sin_slope[95] = 8'sh14;
rom_cos_base[95]  = 12'h64b;
rom_cos_slope[95] = -8'sh2f;

rom_sin_base[96]  = 12'hec1;
rom_sin_slope[96] = 8'sh13;
rom_cos_base[96]  = 12'h61c;
rom_cos_slope[96] = -8'sh2e;

rom_sin_base[97]  = 12'hed4;
rom_sin_slope[97] = 8'sh12;
rom_cos_base[97]  = 12'h5ee;
rom_cos_slope[97] = -8'sh2f;

rom_sin_base[98]  = 12'hee6;
rom_sin_slope[98] = 8'sh12;
rom_cos_base[98]  = 12'h5bf;
rom_cos_slope[98] = -8'sh2f;

rom_sin_base[99]  = 12'hef8;
rom_sin_slope[99] = 8'sh11;
rom_cos_base[99]  = 12'h590;
rom_cos_slope[99] = -8'sh2f;

rom_sin_base[100]  = 12'hf09;
rom_sin_slope[100] = 8'sh11;
rom_cos_base[100]  = 12'h561;
rom_cos_slope[100] = -8'sh2f;

rom_sin_base[101]  = 12'hf1a;
rom_sin_slope[101] = 8'sh10;
rom_cos_base[101]  = 12'h532;
rom_cos_slope[101] = -8'sh30;

rom_sin_base[102]  = 12'hf2a;
rom_sin_slope[102] = 8'sh0f;
rom_cos_base[102]  = 12'h502;
rom_cos_slope[102] = -8'sh2f;

rom_sin_base[103]  = 12'hf39;
rom_sin_slope[103] = 8'sh0f;
rom_cos_base[103]  = 12'h4d3;
rom_cos_slope[103] = -8'sh30;

rom_sin_base[104]  = 12'hf48;
rom_sin_slope[104] = 8'sh0e;
rom_cos_base[104]  = 12'h4a3;
rom_cos_slope[104] = -8'sh30;

rom_sin_base[105]  = 12'hf56;
rom_sin_slope[105] = 8'sh0e;
rom_cos_base[105]  = 12'h473;
rom_cos_slope[105] = -8'sh31;

rom_sin_base[106]  = 12'hf64;
rom_sin_slope[106] = 8'sh0d;
rom_cos_base[106]  = 12'h442;
rom_cos_slope[106] = -8'sh30;

rom_sin_base[107]  = 12'hf71;
rom_sin_slope[107] = 8'sh0c;
rom_cos_base[107]  = 12'h412;
rom_cos_slope[107] = -8'sh31;

rom_sin_base[108]  = 12'hf7d;
rom_sin_slope[108] = 8'sh0c;
rom_cos_base[108]  = 12'h3e1;
rom_cos_slope[108] = -8'sh30;

rom_sin_base[109]  = 12'hf89;
rom_sin_slope[109] = 8'sh0c;
rom_cos_base[109]  = 12'h3b1;
rom_cos_slope[109] = -8'sh31;

rom_sin_base[110]  = 12'hf95;
rom_sin_slope[110] = 8'sh0a;
rom_cos_base[110]  = 12'h380;
rom_cos_slope[110] = -8'sh31;

rom_sin_base[111]  = 12'hf9f;
rom_sin_slope[111] = 8'sh0a;
rom_cos_base[111]  = 12'h34f;
rom_cos_slope[111] = -8'sh31;

rom_sin_base[112]  = 12'hfa9;
rom_sin_slope[112] = 8'sh0a;
rom_cos_base[112]  = 12'h31e;
rom_cos_slope[112] = -8'sh32;

rom_sin_base[113]  = 12'hfb3;
rom_sin_slope[113] = 8'sh09;
rom_cos_base[113]  = 12'h2ec;
rom_cos_slope[113] = -8'sh31;

rom_sin_base[114]  = 12'hfbc;
rom_sin_slope[114] = 8'sh08;
rom_cos_base[114]  = 12'h2bb;
rom_cos_slope[114] = -8'sh32;

rom_sin_base[115]  = 12'hfc4;
rom_sin_slope[115] = 8'sh08;
rom_cos_base[115]  = 12'h289;
rom_cos_slope[115] = -8'sh31;

rom_sin_base[116]  = 12'hfcc;
rom_sin_slope[116] = 8'sh07;
rom_cos_base[116]  = 12'h258;
rom_cos_slope[116] = -8'sh32;

rom_sin_base[117]  = 12'hfd3;
rom_sin_slope[117] = 8'sh06;
rom_cos_base[117]  = 12'h226;
rom_cos_slope[117] = -8'sh32;

rom_sin_base[118]  = 12'hfd9;
rom_sin_slope[118] = 8'sh06;
rom_cos_base[118]  = 12'h1f4;
rom_cos_slope[118] = -8'sh31;

rom_sin_base[119]  = 12'hfdf;
rom_sin_slope[119] = 8'sh05;
rom_cos_base[119]  = 12'h1c3;
rom_cos_slope[119] = -8'sh32;

rom_sin_base[120]  = 12'hfe4;
rom_sin_slope[120] = 8'sh05;
rom_cos_base[120]  = 12'h191;
rom_cos_slope[120] = -8'sh32;

rom_sin_base[121]  = 12'hfe9;
rom_sin_slope[121] = 8'sh04;
rom_cos_base[121]  = 12'h15f;
rom_cos_slope[121] = -8'sh32;

rom_sin_base[122]  = 12'hfed;
rom_sin_slope[122] = 8'sh03;
rom_cos_base[122]  = 12'h12d;
rom_cos_slope[122] = -8'sh32;

rom_sin_base[123]  = 12'hff0;
rom_sin_slope[123] = 8'sh03;
rom_cos_base[123]  = 12'h0fb;
rom_cos_slope[123] = -8'sh32;

rom_sin_base[124]  = 12'hff3;
rom_sin_slope[124] = 8'sh02;
rom_cos_base[124]  = 12'h0c9;
rom_cos_slope[124] = -8'sh33;

rom_sin_base[125]  = 12'hff5;
rom_sin_slope[125] = 8'sh02;
rom_cos_base[125]  = 12'h096;
rom_cos_slope[125] = -8'sh32;

rom_sin_base[126]  = 12'hff7;
rom_sin_slope[126] = 8'sh01;
rom_cos_base[126]  = 12'h064;
rom_cos_slope[126] = -8'sh32;

rom_sin_base[127]  = 12'hff8;
rom_sin_slope[127] = 8'sh00;
rom_cos_base[127]  = 12'h032;
rom_cos_slope[127] = -8'sh32;

