#!/usr/bin/env python3
"""
gen_sincos_interp.py — Generate quarter-wave sin/cos interpolation ROM contents.

Default output is a Verilog include file with explicit assignments:
    rom_sin_base[0]  = ...;
    rom_sin_slope[0] = ...;
    rom_cos_base[0]  = ...;
    rom_cos_slope[0] = ...;

Each coarse entry spans one quarter-wave interval:
    theta0 =  k    * (pi/2) / DEPTH
    theta1 = (k+1) * (pi/2) / DEPTH

Stored values:
    sin_base  = round(scale * sin(theta0))
    sin_slope = round(scale * sin(theta1)) - sin_base
    cos_base  = round(scale * cos(theta0))
    cos_slope = round(scale * cos(theta1)) - cos_base

where:
    scale = (2^MAG_W - 1) << GUARD_W

Usage:
    python3 gen_sincos_interp.py [SINE_TRUNC_W] [MAG_W] [COARSE_W]
                                 [GUARD_W] [SLOPE_W] [output_file]

Defaults:
    SINE_TRUNC_W = 14
    MAG_W        = 9
    COARSE_W     = 7
    GUARD_W      = 3
    SLOPE_W      = 8
    output_file  = rtl/datapath/sincos_interp_init.v
"""

from __future__ import annotations

import math
import sys


def twos_comp(value: int, width: int) -> int:
    return value & ((1 << width) - 1)


def signed_literal(width: int, value: int, hex_w: int) -> str:
    if value < 0:
        return f"-{width}'sh{abs(value):0{hex_w}x}"
    return f"{width}'sh{value:0{hex_w}x}"


def table_values(sine_trunc_w: int, mag_w: int, coarse_w: int, guard_w: int, slope_w: int):
    sine_addr_w = sine_trunc_w - 2
    frac_w = sine_addr_w - coarse_w
    depth = 1 << coarse_w
    scale = ((1 << mag_w) - 1) << guard_w
    slope_min = -(1 << (slope_w - 1))
    slope_max = (1 << (slope_w - 1)) - 1
    rows = []

    if sine_trunc_w < 4:
        raise ValueError("SINE_TRUNC_W must be >= 4")
    if coarse_w < 1:
        raise ValueError("COARSE_W must be >= 1")
    if frac_w < 1:
        raise ValueError("SINE_TRUNC_W - 2 - COARSE_W must be >= 1")
    if slope_w < 2:
        raise ValueError("SLOPE_W must be >= 2")

    for idx in range(depth):
        theta0 = idx * (math.pi / 2.0) / depth
        theta1 = (idx + 1) * (math.pi / 2.0) / depth

        sin_base = int(round(scale * math.sin(theta0)))
        sin_next = int(round(scale * math.sin(theta1)))
        cos_base = int(round(scale * math.cos(theta0)))
        cos_next = int(round(scale * math.cos(theta1)))

        sin_slope = sin_next - sin_base
        cos_slope = cos_next - cos_base

        if not (0 <= sin_base <= scale):
            raise ValueError(f"sin_base[{idx}] out of range: {sin_base}")
        if not (0 <= cos_base <= scale):
            raise ValueError(f"cos_base[{idx}] out of range: {cos_base}")
        if not (slope_min <= sin_slope <= slope_max):
            raise ValueError(f"sin_slope[{idx}]={sin_slope} does not fit SLOPE_W={slope_w}")
        if not (slope_min <= cos_slope <= slope_max):
            raise ValueError(f"cos_slope[{idx}]={cos_slope} does not fit SLOPE_W={slope_w}")

        rows.append((sin_base, sin_slope, cos_base, cos_slope))

    return rows, frac_w, depth, scale


def write_verilog(rows, base_w: int, slope_w: int, outfile: str) -> str:
    base_hex_w = (base_w + 3) // 4
    slope_hex_w = (slope_w + 3) // 4

    with open(outfile, "w", encoding="ascii") as f:
        f.write("// Generated by scripts/gen_sincos_interp.py. Do not edit by hand.\n\n")
        for idx, (sin_base, sin_slope, cos_base, cos_slope) in enumerate(rows):
            f.write(f"rom_sin_base[{idx}]  = {base_w}'h{sin_base:0{base_hex_w}x};\n")
            f.write(f"rom_sin_slope[{idx}] = {signed_literal(slope_w, sin_slope, slope_hex_w)};\n")
            f.write(f"rom_cos_base[{idx}]  = {base_w}'h{cos_base:0{base_hex_w}x};\n")
            f.write(f"rom_cos_slope[{idx}] = {signed_literal(slope_w, cos_slope, slope_hex_w)};\n")
            f.write("\n")

    return f"{base_hex_w} hex digits/base, {slope_hex_w} hex digits/slope"


def write_hex(rows, base_w: int, slope_w: int, outfile: str) -> str:
    packed_w = 2 * base_w + 2 * slope_w
    packed_hex_w = (packed_w + 3) // 4

    with open(outfile, "w", encoding="ascii") as f:
        for sin_base, sin_slope, cos_base, cos_slope in rows:
            packed = (
                (sin_base << (base_w + 2 * slope_w))
                | (twos_comp(sin_slope, slope_w) << (base_w + slope_w))
                | (cos_base << slope_w)
                | twos_comp(cos_slope, slope_w)
            )
            f.write(f"{packed:0{packed_hex_w}x}\n")

    return f"{packed_hex_w} hex digits/entry"


def generate_table(sine_trunc_w: int, mag_w: int, coarse_w: int, guard_w: int, slope_w: int, outfile: str):
    base_w = mag_w + guard_w
    rows, frac_w, depth, scale = table_values(sine_trunc_w, mag_w, coarse_w, guard_w, slope_w)

    if outfile.endswith(".hex"):
        fmt = write_hex(rows, base_w, slope_w, outfile)
    else:
        fmt = write_verilog(rows, base_w, slope_w, outfile)

    first = rows[0]
    mid = rows[len(rows) // 2]
    last = rows[-1]

    print("Generating sin/cos interpolation LUT:")
    print(f"  SINE_TRUNC_W={sine_trunc_w}, MAG_W={mag_w}, COARSE_W={coarse_w}, FRAC_W={frac_w}")
    print(f"  GUARD_W={guard_w}, BASE_W={base_w}, SLOPE_W={slope_w}, SCALE={scale}")
    print(f"  {outfile}: {depth} entries, {fmt}")
    print(f"  entry[0]   = sin({first[0]}, {first[1]}) cos({first[2]}, {first[3]})")
    print(f"  entry[{len(rows)//2}] = sin({mid[0]}, {mid[1]}) cos({mid[2]}, {mid[3]})")
    print(f"  entry[{len(rows)-1}] = sin({last[0]}, {last[1]}) cos({last[2]}, {last[3]})")


if __name__ == "__main__":
    sine_trunc_w = int(sys.argv[1]) if len(sys.argv) > 1 else 14
    mag_w = int(sys.argv[2]) if len(sys.argv) > 2 else 9
    coarse_w = int(sys.argv[3]) if len(sys.argv) > 3 else 7
    guard_w = int(sys.argv[4]) if len(sys.argv) > 4 else 3
    slope_w = int(sys.argv[5]) if len(sys.argv) > 5 else 8
    outfile = sys.argv[6] if len(sys.argv) > 6 else "rtl/datapath/sincos_interp_init.v"

    generate_table(sine_trunc_w, mag_w, coarse_w, guard_w, slope_w, outfile)
