#!/usr/bin/env python3
"""
gen_sine_lut.py — Generate quarter-wave sine ROM contents for DDS

Default output is a Verilog include file with explicit ROM assignments:
    rom[0] = ...;
    rom[1] = ...;
    ...

This lets the ROM live in source control as Verilog and removes the need
for a runtime $readmemh side file. For compatibility, writing a .hex output
path still emits the previous readmemh-style format.

Stores unsigned magnitude = round(MAG_MAX * sin(theta))
where MAG_MAX = 2^MAG_W - 1.

The magnitude splits at the DAC segmentation boundary:
  M[MAG_W-1 : BINARY_BITS]  → unary offset from midscale (thermometer)
  M[BINARY_BITS-1 : 0]      → binary sub-DAC switch pattern (wire)

Usage:
    python3 gen_sine_lut.py [TRUNC_W] [MAG_W] [output_file]

Defaults:
    TRUNC_W     = 12  → quarter-wave depth = 2^(12-2) = 1024 entries
    MAG_W       = 9   → max magnitude = 511
    output_file = rtl/datapath/sine_lut_init.v
"""

import sys
import math


def lut_values(trunc_w, mag_w):
    addr_w  = trunc_w - 2
    depth   = 1 << addr_w
    mag_max = (1 << mag_w) - 1
    values = []

    for i in range(depth):
        theta = i * (math.pi / 2.0) / depth
        val   = int(round(mag_max * math.sin(theta)))
        values.append(min(val, mag_max))

    return values


def write_hex(values, mag_w, outfile):
    hex_w = (mag_w + 3) // 4
    with open(outfile, "w") as f:
        for val in values:
            f.write(f"{val:0{hex_w}x}\n")

    return f"{hex_w} hex digits/entry"


def write_verilog(values, mag_w, outfile):
    hex_w = (mag_w + 3) // 4
    with open(outfile, "w") as f:
        f.write("// Generated by scripts/gen_sine_lut.py. Do not edit by hand.\n")
        for idx, val in enumerate(values):
            f.write(f"        rom[{idx}] = {mag_w}'h{val:0{hex_w}x};\n")

    return f"{hex_w} hex digits/value"


def generate_lut(trunc_w, mag_w, outfile):
    values  = lut_values(trunc_w, mag_w)
    depth   = len(values)
    mag_max = (1 << mag_w) - 1
    hex_w   = (mag_w + 3) // 4

    if outfile.endswith(".hex"):
        fmt = write_hex(values, mag_w, outfile)
    else:
        fmt = write_verilog(values, mag_w, outfile)

    print(f"  {outfile}: {depth} entries, {mag_w}-bit (max={mag_max}), {fmt}")
    print(f"  ROM[0]      = {0:0{hex_w}x}  (sin 0)")
    mid = depth // 2
    mid_theta = mid * (math.pi / 2.0) / depth
    mid_val = values[mid]
    print(f"  ROM[{mid}]   = {mid_val:0{hex_w}x}  (sin {math.degrees(mid_theta):.1f}°)")
    top_theta = (depth - 1) * (math.pi / 2.0) / depth
    top_val = values[-1]
    print(f"  ROM[{depth-1}] = {top_val:0{hex_w}x}  (sin {math.degrees(top_theta):.1f}°)")


if __name__ == "__main__":
    trunc_w = int(sys.argv[1]) if len(sys.argv) > 1 else 12
    mag_w   = int(sys.argv[2]) if len(sys.argv) > 2 else 9
    outfile = sys.argv[3]      if len(sys.argv) > 3 else "rtl/datapath/sine_lut_init.v"

    print(f"Generating quarter-wave sine LUT:")
    print(f"  TRUNC_W={trunc_w}, MAG_W={mag_w}")
    generate_lut(trunc_w, mag_w, outfile)
