`default_nettype none
`timescale 1ns/1ps

// Amplitude scaler — CSA multiply, carry-save output.
//
// Outputs carry-save upper bits + c16 for deferred resolution.
// The downstream pipeline stage resolves with a 9-bit carry-select:
//   scaled = ws_hi + wc_hi + c16
//
// This moves the 25-bit CPA out of this stage entirely.
// S3 (this module): Wallace tree only.
// S4 (downstream):  9-bit carry-select + DAC encode.
//
(* keep_hierarchy = "yes" *)
module amp_scale #(
    parameter MAG_W = 9,
    parameter AMP_W = 16
)(
    input  logic              clk,
    input  logic              rst_n,

    input  logic [MAG_W-1:0] mag,
    input  logic [AMP_W-1:0] amp_in,    // from S1 — registered internally

    // carry-save output — upper MAG_W bits after >> AMP_W
    output logic [MAG_W-1:0] ws_hi,
    output logic [MAG_W-1:0] wc_hi,
    output logic              c16,      // carry-out from lower AMP_W bits

    output logic              is_zero
);

    localparam PW = MAG_W + AMP_W;  // 25

    // ================================================================
    //  Internal amp register — replaces amp_2 in parent.
    //  Parent drives 2 module ports instead of 165 gates.
    //  This FF is inside keep_hierarchy — ABC can't merge it
    //  with anything outside.
    // ================================================================
    logic [AMP_W-1:0] amp;

    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n)
            amp <= {AMP_W{1'b1}};   // unity default
        else
            amp <= amp_in;
    end

    // ================================================================
    //  Partial products
    // ================================================================
    wire [PW-1:0] pp [0:MAG_W-1];

    genvar gi;
    generate
        for (gi = 0; gi < MAG_W; gi = gi + 1) begin : gen_pp
            assign pp[gi] = ({{(MAG_W-1){1'b0}}, amp} & {PW{mag[gi]}}) << gi;
        end
    endgenerate

    // Rounding constant: 1 << (AMP_W - 1)
    localparam [PW-1:0] ROUND = {{(PW-AMP_W){1'b0}}, 1'b1, {(AMP_W-1){1'b0}}};

    // ================================================================
    //  CSA tree: 10 terms → {ws, wc}
    // ================================================================

    // --- Layer 1: 10 → 7 ---
    wire [PW-1:0] s0  = pp[0] ^ pp[1] ^ pp[2];
    wire [PW-1:0] m0  = (pp[0]&pp[1]) | (pp[0]&pp[2]) | (pp[1]&pp[2]);
    wire [PW-1:0] c0  = {m0[PW-2:0], 1'b0};

    wire [PW-1:0] s1  = pp[3] ^ pp[4] ^ pp[5];
    wire [PW-1:0] m1  = (pp[3]&pp[4]) | (pp[3]&pp[5]) | (pp[4]&pp[5]);
    wire [PW-1:0] c1  = {m1[PW-2:0], 1'b0};

    wire [PW-1:0] s2  = pp[6] ^ pp[7] ^ pp[8];
    wire [PW-1:0] m2  = (pp[6]&pp[7]) | (pp[6]&pp[8]) | (pp[7]&pp[8]);
    wire [PW-1:0] c2  = {m2[PW-2:0], 1'b0};

    // --- Layer 2: 7 → 5 ---
    wire [PW-1:0] s3  = s0 ^ c0 ^ s1;
    wire [PW-1:0] m3  = (s0&c0) | (s0&s1) | (c0&s1);
    wire [PW-1:0] c3  = {m3[PW-2:0], 1'b0};

    wire [PW-1:0] s4  = c1 ^ s2 ^ c2;
    wire [PW-1:0] m4  = (c1&s2) | (c1&c2) | (s2&c2);
    wire [PW-1:0] c4  = {m4[PW-2:0], 1'b0};

    // --- Layer 3: 5 → 4 ---
    wire [PW-1:0] s5  = s3 ^ c3 ^ s4;
    wire [PW-1:0] m5  = (s3&c3) | (s3&s4) | (c3&s4);
    wire [PW-1:0] c5  = {m5[PW-2:0], 1'b0};

    // --- Layer 4: 4 → 3 ---
    wire [PW-1:0] s6  = s5 ^ c5 ^ c4;
    wire [PW-1:0] m6  = (s5&c5) | (s5&c4) | (c5&c4);
    wire [PW-1:0] c6  = {m6[PW-2:0], 1'b0};

    // --- Layer 5: 3 → 2 (inject ROUND) ---
    wire [PW-1:0] ws  = s6 ^ c6 ^ ROUND;
    wire [PW-1:0] mw  = (s6&c6) | (s6&ROUND) | (c6&ROUND);
    wire [PW-1:0] wc  = {mw[PW-2:0], 1'b0};

    // ================================================================
    //  Extract upper bits (just wires — zero logic depth)
    // ================================================================
    assign ws_hi = ws[PW-1:AMP_W];
    assign wc_hi = wc[PW-1:AMP_W];

    // ================================================================
    //  c16: carry-out from lower AMP_W bits.
    //
    //  We need the carry generated by ws[15:0] + wc[15:0].
    //  This is a single-bit output — we only need the group carry,
    //  not the full sum.  Let ABC map this as it sees fit internally.
    // ================================================================
    wire [AMP_W:0] lower_sum = {1'b0, ws[AMP_W-1:0]} + {1'b0, wc[AMP_W-1:0]};
    assign c16 = lower_sum[AMP_W];

    assign is_zero = (amp == {AMP_W{1'b0}});

endmodule
